version: "3"

services:
  app:
    build: ./
    restart: unless-stopped
    ports:
      - '4000:4000'
    volumes:
      - .:/app
    networks:
      - backend
  db:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - ./docker/mysql/:/docker-entrypoint-initdb.d/
      - db:/var/lib/mysql/
    depends_on:
      - app
    ports:
      - 3306:3306
    networks:
      - backend
    environment:
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: devuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      
volumes:
  db:

networks:
  backend: 